version: '3.9'

services:
  mongodb:
    container_name: account_mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME= account_service
      - MONGO_INITDB_ROOT_PASSWORD= account_service
    ports:
      - '27017:27017'
