spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: account-service
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}
  config:
    import:
      - optional:classpath:./variables-local.properties
      - optional:configserver:http://localhost:8088
  kafka:
    producer:
      bootstrap-servers: localhost:9092


springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: ERROR
    com.ticketconnect.accountservice: INFO